### PR TITLE
Motorola S-format and SidForth-83 custom device support

### PR DESCRIPTION
**Pull request by jty**
HI, I have some very old code for a custom made 6809 computer that I wanted  to run, so took your emulator, added support for Motorola S-format hexfiles and a simulated sidforth disk and tty.
I rearranged a bit the way main() works, had to do some #define magic as I did not want to do large refactoring. I have >10k lines assembly file that compiles with jty/as9 and now runs on the emulator nicely!
Thanks a lot for sharing this code.

### CODE REVIEW

**Comment by raybellis** [comment]
Hi there - your code on the whole isn't suitable for merging into the main line project, but I will go through it and see if there are little chunks of it that might be of use.

**Comment by jty** [comment]
I’ll be happy to make it suitable, but the challenge is the selection of the actual simulated device (peripherals).
Do you have plans/idea how to suppor multiple devices?
If not, I can draft something, maybe along the lines building separate binary for each device (requiring somewhat nasty #define magic for inheritance).
Alternatively, main() could have a static array of devices and select with a switch at runtime

**Comment by jty** [comment]
Further... there are many 6809 emulators around, but imo the merit of yours is the simplicity to modify it for a particular (embedded) device.
Thus, making ot even easier to add another device would be nice

**Comment by raybellis** [comment]
It was never really the intention that the code be completely usable for all embedded situations without needing to make _some_ sort of modifications, especially in the code where various addresses are mapped to I/O peripherals.   I'd potentially like to improve that, but it's low priority for me just now with other projects going on (and this code is 25 years old now!)

**Comment by jty** [comment]
Ok, so i will keep my branch. The Motorola S-format is in one commit, should be easy to cherrypick

**Comment by raybellis** [comment]
@jty you might want to look at the latest updates which change the device attachment model from compile-time inheritance to run-time linking of `Device` objects to the CPU.

**Pull request closed without merging**
